#!/bin/bash

# Install git prompt in home
echo "Cloning bash-git-prompt Github repository..."
[ ! -d "$HOME/.bash-git-prompt" ] && git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1

# Sync files
# TODO: Call sync script
