#!/bin/bash

sudo apt-get update

# Curl
sudo apt-get install curl -y

# Python
sudo apt-get install python3-pip -y

# ZSH
sudo apt-get install zsh -y

# Oh my ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install latest NVM 
sudo curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
npm install -g npm@latest

# Install stable Node with npm
nvm install stable

# Copy .zshrc  
cp ~/.dotfiles/.zshrc ~/.zshrc

# Reload profile
source ~/.zshrc

