#!/usr/bin/env bash
#
# Run all dotfiles installers.

# Exit if any error is found during process
set -e

# Go to dotfiles root dir
cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
